name: mov
channels:
  - conda-forge
  #- plotly
dependencies:
  - python=3.12
  - pip=24.0 
  - pandas=2.2.2
  - geopandas=0.14.4
  - polars=0.20.26
  - numpy=1.26.4
  - ipykernel=6.29.3
  - dash=2.17.0
  - pyarrow=16.1.0
  - psycopg2=2.9.9
  - sqlalchemy=2.0.31
  - geoalchemy2=0.15.1
  - nbformat=5.10.4
  - requests=2.32.3 
  - pip:
      - geoarrow-rust-core==0.2.0
      - python-dotenv==1.0.1
      - pyogrio==0.8.0
      - cpi==2.0.2 
